-- MySQL Script generated by MySQL Workbench
-- 09/25/14 09:42:04
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema rmsystem
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `rmsystem` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `rmsystem` ;

-- -----------------------------------------------------
-- Table `rmsystem`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rmsystem`.`user` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NULL,
  `last_name` VARCHAR(45) NULL,
  `address_line_1` VARCHAR(45) NULL,
  `address_line_2` VARCHAR(45) NULL,
  `city` VARCHAR(45) NULL,
  `state` VARCHAR(45) NULL,
  `zip_code` VARCHAR(45) NULL,
  `birth_date` VARCHAR(45) NULL,
  `role` VARCHAR(45) NOT NULL DEFAULT 'member',
  `reward_points` VARCHAR(45) NOT NULL DEFAULT 0,
  `reward_tier` VARCHAR(45) NULL DEFAULT 'tier_1',
  `email` VARCHAR(45) NULL,
  `password` VARCHAR(45) NOT NULL,
  `cc_number` VARCHAR(45) NULL,
  `cc_expire` VARCHAR(45) NULL,
  `cc_cvv` VARCHAR(45) NULL,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rmsystem`.`retailer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rmsystem`.`retailer` (
  `retailer_id` INT NOT NULL AUTO_INCREMENT,
  `private_key` VARCHAR(256) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`retailer_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rmsystem`.`transaction`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rmsystem`.`transaction` (
  `transaction_id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `retailer_id` INT NOT NULL,
  `amount_spent` VARCHAR(45) NOT NULL DEFAULT '0.00',
  `transaction_dt` DATETIME NOT NULL,
  PRIMARY KEY (`transaction_id`),
  INDEX `retailer_id_idx` (`retailer_id` ASC),
  INDEX `user_id_idx` (`user_id` ASC),
  CONSTRAINT `user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `rmsystem`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `retailer_id`
    FOREIGN KEY (`retailer_id`)
    REFERENCES `rmsystem`.`retailer` (`retailer_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rmsystem`.`tier_transaction`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rmsystem`.`tier_transaction` (
  `tier_transaction_id` INT NOT NULL AUTO_INCREMENT,
  `tier_user_id` INT NOT NULL,
  `new_reward_tier` VARCHAR(45) NOT NULL,
  `tier_transaction_dt` DATETIME NOT NULL,
  PRIMARY KEY (`tier_transaction_id`),
  INDEX `user_id_idx` (`tier_user_id` ASC),
  CONSTRAINT `tier_user_id`
    FOREIGN KEY (`tier_user_id`)
    REFERENCES `rmsystem`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
